### ISSUE TITLE
Add config file support for profiles

### ISSUE THREAD

**Issue by toumorokoshi** [aep-dev/aepcli#1]
Adding a config file that supports profiles would allow for a very fluid interface. We could have different contexts like:

```toml
[roblox]
openapi_file= "/path/to/openapi.json"
headers = [
  "x-aep-key=SOME_API_KEY"
]
```

Which we could then read as a profile that could be set like:

```bash
aecpli roblox users get 123
```
